github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

ports:
  - port: 3000
    onOpen: notify
  - port: 3306
    onOpen: ignore
  - port: 8080
    onOpen: open-browser

tasks:
  - init: >
      docker-compose pull &&
      npm install -g pnpm &&
      pnpm install
    command: >
      npm install -g pnpm &&
      pnpm prisma:bootstrap &&
      pnpm dev
  - name: Database service
    command: docker-compose up
